In [8]:
import math
import numpy as np
import random
from random import randint
from gurobipy import *
#import pandas as pd
from random import seed
import matplotlib.pyplot as plt
import geopy.distance

In [9]:
#path = r"C:/Users/Devika Kabe/Documents/Model_brainstorming/"
path = "/home/dkabe/Model_brainstorming/"

In [10]:
f = open(path + 'Input_Data/product_distributions.txt', 'r')
text = f.read()
f.close()
distributions = text.split('\n')

In [11]:
for i in distributions:
    exec(i.lstrip().rstrip())

In [12]:
distribution_mat = np.array([[p1_mean, p1_sd],
                             [p2_mean, p2_sd],
                             [p3_mean, p3_sd],
                             [p4_mean, p4_sd]])

In [13]:
distribution_mat

array([[2487.        ,   70.71067812],
       [2329.        ,   42.42640687],
       [2539.        ,   14.14213562],
       [2302.        ,   56.56854249]])

## 2 Products, 2 Outsourced Suppliers

In [49]:
Products = 2
Outsourced = 2

In [50]:
## 2 MPs, 3 DCs, 4 MZs
## 2 Products, 2 Outsourced Facilities 

Manufacturing_plants = 2
Distribution = 3
num_Scenarios = (2**Manufacturing_plants)*(2**Distribution) 
Market = 1

# Cost of opening
f_i = [7500, 12500]
f_j = [7500, 12500, 17500]

# Unit cost of manufacturing product
np.random.seed(0)
Manufacturing_costs = np.random.uniform(0,1, (Manufacturing_plants,Products))

# Unit cost of transporting m from plant to DC
np.random.seed(0)
Transportation_i_j = np.random.uniform(0,1, (Products, Manufacturing_plants, Distribution))

# Unit cost of transporting m from DC to Market Zone
np.random.seed(0)
Transportation_j_k = np.random.uniform(0,1, (Products, Distribution, Market))

# Plant Capacities: Bigger capacities for the more expensive ones
np.random.seed(0)
Capacities_i = np.zeros(Manufacturing_plants) # in volume (metres cubed)
Capacities_i[0] = 5000
Capacities_i[1] = 10000

Capacities_j = np.zeros(Distribution) # in volume (metres cubed)
Capacities_j[0] = 5000
Capacities_j[1] = 10000
Capacities_j[2] = 15000

Capacities_l = np.random.randint(400, 500, (Products,Outsourced)) # in terms of products 

# Cost of purchasing product m from supplier l 
np.random.seed(0)
levels = 2
Supplier_cost = np.zeros((levels, Products, Outsourced))
Supplier_cost[0] = np.random.uniform(17, 20, (Products, Outsourced))
Supplier_cost[1] = np.random.uniform(20, 23, (Products, Outsourced))

# Cost of transporting product m from outsourced facility l to j
np.random.seed(0)
T_O_DC = np.random.uniform(1, 2, (Products, Outsourced, Distribution))

# Cost of shipping product m from outsourced facility l to k
np.random.seed(0)
T_O_MZ = np.random.uniform(2, 3,(Products, Outsourced, Market))

# Product volume 
np.random.seed(0)
volume = np.random.uniform(1, 2,(Products))

# unit cost of lost sales 
np.random.seed(1)
lost_sales = np.random.uniform(20, 25, (Market,Products))

# Demand
demand = np.zeros((num_Scenarios, Products, Market))
np.random.seed(0)
for s in range(num_Scenarios):
    for k in range(Market):
        for m in range(Products):
            demand[s][m][k] = np.round(np.random.normal(distribution_mat[m][0], distribution_mat[m][1]))

# Compatibilities
compatibility = np.ones((Products, Manufacturing_plants))

In [51]:
compatibilty

array([[1., 1.],
       [1., 1.]])

In [52]:
lost_sales

array([[22.08511002, 23.60162247]])

In [53]:
Supplier_cost

array([[[18.64644051, 19.1455681 ],
        [18.80829013, 18.63464955]],

       [[21.2709644 , 21.93768234],
        [21.31276163, 22.675319  ]]])

In [54]:
np.sum(demand[0])

4958.0

In [55]:
# save files 
np.savetxt(path + 'Input_Data/Instance_1/OpenMP_1.txt', f_i)
np.savetxt(path + 'Input_Data/Instance_1/OpenDC_1.txt', f_j)
np.savetxt(path + 'Input_Data/Instance_1/Manufacturing_1.txt', Manufacturing_costs)
np.savetxt(path + 'Input_Data/Instance_1/TransMPDC_1.txt', Transportation_i_j.reshape((Products*Manufacturing_plants, Distribution)))
np.savetxt(path + 'Input_Data/Instance_1/TransDCMZ_1.txt', Transportation_j_k.reshape((Products*Distribution, Market)))
np.savetxt(path + 'Input_Data/Instance_1/CapacitiesMP_1.txt', Capacities_i)
np.savetxt(path + 'Input_Data/Instance_1/CapacitiesDC_1.txt', Capacities_j)
np.savetxt(path + 'Input_Data/Instance_1/CapacitiesOutsource_1.txt', Capacities_l)
np.savetxt(path + 'Input_Data/Instance_1/SupplierCost_1.txt', Supplier_cost.reshape((levels*Products, Outsourced)))
np.savetxt(path + 'Input_Data/Instance_1/TransSupplierDC_1.txt', T_O_DC.reshape((Products*Outsourced, Distribution)))
np.savetxt(path + 'Input_Data/Instance_1/TransSupplierMZ_1.txt', T_O_MZ.reshape((Products*Outsourced, Market)))
np.savetxt(path + 'Input_Data/Instance_1/Volume_1.txt', volume)
np.savetxt(path + 'Input_Data/Instance_1/LostSales_1.txt', lost_sales)
np.savetxt(path + 'Input_Data/Instance_1/Demand_1.txt', demand.reshape((num_Scenarios*Products, Market)))
np.savetxt(path + 'Input_Data/Instance_1/Compatibilities_1.txt', compatibility)


In [56]:
## 3 MPs, 4 DCs, 2 MZs

num_Scenarios = 128

Manufacturing_plants = 3
Distribution = 4
Market = 2
Outsourced = 2

# Cost of opening
f_i = [7500, 12500, 17500]
f_j = [7500, 12500, 17500, 7500]

# Unit cost of manufacturing product
np.random.seed(0)
Manufacturing_costs = np.random.uniform(0,1, (Manufacturing_plants,Products))

# Unit cost of transporting m from plant to DC
np.random.seed(0)
Transportation_i_j = np.random.uniform(0,1, (Products, Manufacturing_plants, Distribution))

# Unit cost of transporting m from DC to Market Zone
np.random.seed(0)
Transportation_j_k = np.random.uniform(0,1, (Products, Distribution, Market))

# Plant Capacities: Bigger capacities for the more expensive ones
np.random.seed(0)
Capacities_i = np.zeros(Manufacturing_plants) # in volume (metres cubed)
Capacities_i[0] = 5000
Capacities_i[1] = 10000
Capacities_i[2] = 15000
Capacities_j = np.zeros(Distribution) # in volume (metres cubed)
Capacities_j[0] = 5000
Capacities_j[1] = 10000
Capacities_j[2] = 15000
Capacities_j[3] = 5000
Capacities_l = np.random.randint(800, 1000, (Products,Outsourced)) # in terms of products 

# Cost of purchasing product m from supplier l 
np.random.seed(0)
levels = 2
Supplier_cost = np.zeros((levels, Products, Outsourced))
Supplier_cost[0] = np.random.uniform(17, 20, (Products, Outsourced))
Supplier_cost[1] = np.random.uniform(20, 23, (Products, Outsourced))

# Cost of transporting product m from outsourced facility l to j
np.random.seed(0)
T_O_DC = np.random.uniform(1, 2, (Products, Outsourced, Distribution))

# Cost of shipping product m from outsourced facility l to k
np.random.seed(0)
T_O_MZ = np.random.uniform(2, 3,(Products, Outsourced, Market))

# Product volume 
np.random.seed(0)
volume = np.random.uniform(1, 2,(Products))

# unit cost of lost sales 
np.random.seed(1)
lost_sales = np.random.uniform(20, 25, (Market,Products))

# Demand
demand = np.zeros((num_Scenarios, Products, Market))
np.random.seed(0)
for s in range(num_Scenarios):
    for k in range(Market):
        for m in range(Products):
            demand[s][m][k] = np.round(np.random.normal(distribution_mat[m][0], distribution_mat[m][1]))

# Compatibilities
compatibility = np.ones((Products, Manufacturing_plants))

In [57]:
compatibility

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.savetxt(path + 'Input_Data/Instance_2/OpenMP_2.txt', f_i)
np.savetxt(path + 'Input_Data/Instance_2/OpenDC_2.txt', f_j)
np.savetxt(path + 'Input_Data/Instance_2/Manufacturing_2.txt', Manufacturing_costs)
np.savetxt(path + 'Input_Data/Instance_2/TransMPDC_2.txt', Transportation_i_j.reshape((Products*Manufacturing_plants, Distribution)))
np.savetxt(path + 'Input_Data/Instance_2/TransDCMZ_2.txt', Transportation_j_k.reshape((Products*Distribution, Market)))
np.savetxt(path + 'Input_Data/Instance_2/CapacitiesMP_2.txt', Capacities_i)
np.savetxt(path + 'Input_Data/Instance_2/CapacitiesDC_2.txt', Capacities_j)
np.savetxt(path + 'Input_Data/Instance_2/CapacitiesOutsource_2.txt', Capacities_l)
np.savetxt(path +'Input_Data/Instance_2/SupplierCost_2.txt', Supplier_cost.reshape((levels*Products, Outsourced)))
np.savetxt(path + 'Input_Data/Instance_2/TransSupplierDC_2.txt', T_O_DC.reshape((Products*Outsourced, Distribution)))
np.savetxt(path + 'Input_Data/Instance_2/TransSupplierMZ_2.txt', T_O_MZ.reshape((Products*Outsourced, Market)))
np.savetxt(path + 'Input_Data/Instance_2/Volume_2.txt', volume)
np.savetxt(path + 'Input_Data/Instance_2/LostSales_2.txt', lost_sales)
np.savetxt(path + 'Input_Data/Instance_2/Demand_2.txt', demand.reshape((num_Scenarios*Products, Market)))
np.savetxt(path + 'Input_Data/Instance_2/Compatibilities_2.txt', compatibility)


In [59]:
## 4 MPs, 6 DCs, 3 MZs

num_Scenarios = 200
Manufacturing_plants = 4
Distribution = 6
Market = 3
Products = 2
Outsourced = 2
# Cost of opening
f_i = [7500, 12500, 17500, 7500]
f_j = [7500, 12500, 17500, 7500, 12500, 17500]

# Unit cost of manufacturing product
np.random.seed(0)
Manufacturing_costs = np.random.uniform(0,1, (Manufacturing_plants,Products))

# Unit cost of transporting m from plant to DC
np.random.seed(0)
Transportation_i_j = np.random.uniform(0,1, (Products, Manufacturing_plants, Distribution))

# Unit cost of transporting m from DC to Market Zone
np.random.seed(0)
Transportation_j_k = np.random.uniform(0,1, (Products, Distribution, Market))

# Plant Capacities: Bigger capacities for the more expensive ones
np.random.seed(0)
Capacities_i = np.zeros(Manufacturing_plants) # in volume (metres cubed)
Capacities_i[0] = 5000
Capacities_i[1] = 10000
Capacities_i[2] = 15000
Capacities_i[3] = 5000
Capacities_j = np.zeros(Distribution) # in volume (metres cubed)
Capacities_j[0] = 5000
Capacities_j[1] = 10000
Capacities_j[2] = 15000
Capacities_j[3] = 5000
Capacities_j[4] = 10000
Capacities_j[5] = 15000
Capacities_l = np.random.randint(1200, 1500, (Products,Outsourced)) # in terms of products 

# Cost of purchasing product m from supplier l 
np.random.seed(0)
levels = 2
Supplier_cost = np.zeros((levels, Products, Outsourced))
Supplier_cost[0] = np.random.uniform(17, 20, (Products, Outsourced))
Supplier_cost[1] = np.random.uniform(20, 23, (Products, Outsourced))

# Cost of transporting product m from outsourced facility l to j
np.random.seed(0)
T_O_DC = np.random.uniform(1, 2, (Products, Outsourced, Distribution))

# Cost of shipping product m from outsourced facility l to k
np.random.seed(0)
T_O_MZ = np.random.uniform(2, 3,(Products, Outsourced, Market))

# Product volume 
np.random.seed(0)
volume = np.random.uniform(1, 2,(Products))

# unit cost of lost sales 
np.random.seed(1)
lost_sales = np.random.uniform(20, 25, (Market,Products))

# Demand
demand = np.zeros((num_Scenarios, Products, Market))
np.random.seed(0)
for s in range(num_Scenarios):
    for k in range(Market):
        for m in range(Products):
            demand[s][m][k] = np.round(np.random.normal(distribution_mat[m][0], distribution_mat[m][1]))
# Compatibilities
compatibility = np.ones((Products, Manufacturing_plants))

In [60]:
lost_sales

array([[22.08511002, 23.60162247],
       [20.00057187, 21.51166286],
       [20.73377945, 20.46169297]])

In [61]:
Supplier_cost

array([[[18.64644051, 19.1455681 ],
        [18.80829013, 18.63464955]],

       [[21.2709644 , 21.93768234],
        [21.31276163, 22.675319  ]]])

In [62]:
np.savetxt(path + 'Input_Data/Instance_3/OpenMP_3.txt', f_i)
np.savetxt(path + 'Input_Data/Instance_3/OpenDC_3.txt', f_j)
np.savetxt(path + 'Input_Data/Instance_3/Manufacturing_3.txt', Manufacturing_costs)
np.savetxt(path + 'Input_Data/Instance_3/TransMPDC_3.txt', Transportation_i_j.reshape((Products*Manufacturing_plants, Distribution)))
np.savetxt(path + 'Input_Data/Instance_3/TransDCMZ_3.txt', Transportation_j_k.reshape((Products*Distribution, Market)))
np.savetxt(path + 'Input_Data/Instance_3/CapacitiesMP_3.txt', Capacities_i)
np.savetxt(path + 'Input_Data/Instance_3/CapacitiesDC_3.txt', Capacities_j)
np.savetxt(path + 'Input_Data/Instance_3/CapacitiesOutsource_3.txt', Capacities_l)
np.savetxt(path + 'Input_Data/Instance_3/SupplierCost_3.txt', Supplier_cost.reshape((levels*Products, Outsourced)))
np.savetxt(path + 'Input_Data/Instance_3/TransSupplierDC_3.txt', T_O_DC.reshape((Products*Outsourced, Distribution)))
np.savetxt(path + 'Input_Data/Instance_3/TransSupplierMZ_3.txt', T_O_MZ.reshape((Products*Outsourced, Market)))
np.savetxt(path + 'Input_Data/Instance_3/Volume_3.txt', volume)
np.savetxt(path + 'Input_Data/Instance_3/LostSales_3.txt', lost_sales)
np.savetxt(path + 'Input_Data/Instance_3/Demand_3.txt', demand.reshape((num_Scenarios*Products, Market)))
np.savetxt(path + 'Input_Data/Instance_3/Compatibilities_3.txt', compatibility)


In [63]:
## 6 MPs, 8 DCs, 5 MZs

num_Scenarios = 200
Manufacturing_plants = 6
Distribution = 8
Market = 5

# Cost of opening
f_i = [7500, 12500, 17500, 7500, 12500, 17500]
f_j = [7500, 12500, 17500, 7500, 12500, 17500, 7500, 12500]
# Unit cost of manufacturing product
np.random.seed(0)
Manufacturing_costs = np.random.uniform(0,1, (Manufacturing_plants,Products))

# Unit cost of transporting m from plant to DC
np.random.seed(0)
Transportation_i_j = np.random.uniform(0,1, (Products, Manufacturing_plants, Distribution))

# Unit cost of transporting m from DC to Market Zone
np.random.seed(0)
Transportation_j_k = np.random.uniform(0,1, (Products, Distribution, Market))

# Plant Capacities: Bigger capacities for the more expensive ones
np.random.seed(0)
Capacities_i = np.zeros(Manufacturing_plants) # in volume (metres cubed)
Capacities_i[0] = 5000
Capacities_i[1] = 10000
Capacities_i[2] = 15000
Capacities_i[3] = 5000
Capacities_i[4] = 10000
Capacities_i[5] = 15000
Capacities_j = np.zeros(Distribution) # in volume (metres cubed)
Capacities_j[0] = 5000
Capacities_j[1] = 10000
Capacities_j[2] = 15000
Capacities_j[3] = 5000
Capacities_j[4] = 10000
Capacities_j[5] = 15000
Capacities_j[6] = 5000
Capacities_j[7] = 10000
Capacities_l = np.random.randint(2000, 2500, (Products,Outsourced)) # in terms of products 

# Cost of purchasing product m from supplier l 
np.random.seed(0)
levels = 2
Supplier_cost = np.zeros((levels, Products, Outsourced))
Supplier_cost[0] = np.random.uniform(17, 20, (Products, Outsourced))
Supplier_cost[1] = np.random.uniform(20, 23, (Products, Outsourced))

# Cost of transporting product m from outsourced facility l to j
np.random.seed(0)
T_O_DC = np.random.uniform(1, 2, (Products, Outsourced, Distribution))

# Cost of shipping product m from outsourced facility l to k
np.random.seed(0)
T_O_MZ = np.random.uniform(2, 3,(Products, Outsourced, Market))

# Product volume 
np.random.seed(0)
volume = np.random.uniform(1, 2,(Products))

# unit cost of lost sales 
np.random.seed(1)
lost_sales = np.random.uniform(20, 25, (Market,Products))

# Demand
demand = np.zeros((num_Scenarios, Products, Market))
np.random.seed(0)
for s in range(num_Scenarios):
    for k in range(Market):
        for m in range(Products):
            demand[s][m][k] = np.round(np.random.normal(distribution_mat[m][0], distribution_mat[m][1]))
            
# Compatibilities
compatibility = np.ones((Products, Manufacturing_plants))

In [64]:
np.sum(demand[1])

24339.0

In [65]:
demand

array([[[2612., 2556., 2619., 2554., 2480.],
        [2346., 2424., 2288., 2323., 2346.]],

       [[2497., 2541., 2518., 2593., 2509.],
        [2391., 2334., 2343., 2320., 2293.]],

       [[2306., 2548., 2647., 2490., 2595.],
        [2357., 2298., 2267., 2321., 2391.]],

       ...,

       [[2577., 2488., 2463., 2542., 2430.],
        [2299., 2343., 2328., 2347., 2282.]],

       [[2431., 2476., 2445., 2517., 2398.],
        [2329., 2294., 2265., 2327., 2330.]],

       [[2582., 2580., 2501., 2586., 2406.],
        [2298., 2315., 2333., 2336., 2273.]]])

In [66]:
np.savetxt(path + 'Input_Data/Instance_4/OpenMP_4.txt', f_i)
np.savetxt(path + 'Input_Data/Instance_4/OpenDC_4.txt', f_j)
np.savetxt(path + 'Input_Data/Instance_4/Manufacturing_4.txt', Manufacturing_costs)
np.savetxt(path + 'Input_Data/Instance_4/TransMPDC_4.txt', Transportation_i_j.reshape((Products*Manufacturing_plants, Distribution)))
np.savetxt(path + 'Input_Data/Instance_4/TransDCMZ_4.txt', Transportation_j_k.reshape((Products*Distribution, Market)))
np.savetxt(path + 'Input_Data/Instance_4/CapacitiesMP_4.txt', Capacities_i)
np.savetxt(path + 'Input_Data/Instance_4/CapacitiesDC_4.txt', Capacities_j)
np.savetxt(path + 'Input_Data/Instance_4/CapacitiesOutsource_4.txt', Capacities_l)
np.savetxt(path + 'Input_Data/Instance_4/SupplierCost_4.txt', Supplier_cost.reshape((levels*Products, Outsourced)))
np.savetxt(path + 'Input_Data/Instance_4/TransSupplierDC_4.txt', T_O_DC.reshape((Products*Outsourced, Distribution)))
np.savetxt(path + 'Input_Data/Instance_4/TransSupplierMZ_4.txt', T_O_MZ.reshape((Products*Outsourced, Market)))
np.savetxt(path + 'Input_Data/Instance_4/Volume_4.txt', volume)
np.savetxt(path + 'Input_Data/Instance_4/LostSales_4.txt', lost_sales)
np.savetxt(path + 'Input_Data/Instance_4/Demand_4.txt', demand.reshape((num_Scenarios*Products, Market)))
np.savetxt(path + 'Input_Data/Instance_4/Compatibilities_4.txt', compatibility)


## Mimic real-life scenarios

In [14]:
# Distribution centres and market zones don't change based on instances 

with open (path + "Input_Data/DC_locations.txt") as f:
    DC_locations = [tuple(map(float, i.split('\t'))) for i in f]

with open (path + "Input_Data/market_locations.txt") as f:
    market_locations = [tuple(map(float, i.split('\t'))) for i in f]

# Distribution Centres to Market Zones 
distances_j_k = []
for loc1 in range(len(DC_locations)):
    temp_dist = []
    for loc2 in range(len(market_locations)):
        temp_dist.append(float(str(geopy.distance.geodesic(DC_locations[loc1], market_locations[loc2]))[:-3]))
    distances_j_k.append(temp_dist)

## Cleaning Products

In [15]:
# open location data

In [16]:
with open (path + "Input_Data/Instance_5/MP_locations_5.txt") as f:
    MP_locations = [tuple(map(float, i.split('\t'))) for i in f]

In [17]:
with open(path + "Input_Data/Instance_5/outsource_locations_5.txt") as f:
    outsource_locations = [tuple(map(float, i.split('\t'))) for i in f]

In [18]:
# compute geodesic distances 

In [72]:
# Plants to Distribution Centres
distances_i_j = []
for loc1 in range(len(MP_locations)):
    temp_dist = []
    for loc2 in range(len(DC_locations)):
        temp_dist.append(float(str(geopy.distance.geodesic(MP_locations[loc1], DC_locations[loc2]))[:-3]))
    distances_i_j.append(temp_dist)

In [73]:
# Outsourced Facilities to Distribution Centres
distances_l_j = []
for loc1 in range(len(outsource_locations)):
    temp_dist = []
    for loc2 in range(len(DC_locations)):
        temp_dist.append(float(str(geopy.distance.geodesic(outsource_locations[loc1], DC_locations[loc2]))[:-3]))
    distances_l_j.append(temp_dist)


In [74]:
# Outsourced Facilities to Market Zones
distances_l_k = []
for loc1 in range(len(outsource_locations)):
    temp_dist = []
    for loc2 in range(len(market_locations)):
        temp_dist.append(float(str(geopy.distance.geodesic(outsource_locations[loc1], market_locations[loc2]))[:-3]))
    distances_l_k.append(temp_dist)

In [75]:
# means and sds of products
# p1_mean = 205500
# p2_mean = 202500
# p3_mean = 199500

# p1_sd = 3300
# p2_sd = 8250
# p3_sd = 1650

p1_mean = 103500
p2_mean = 101500
p3_mean = 99750

p1_sd = 1650
p2_sd = 4125
p3_sd = 2000

In [76]:
distribution_mat = [[p1_mean, p1_sd],
                  [p2_mean, p2_sd],
                  [p3_mean, p3_sd]]

In [77]:

## 6 MPs, 4 DCs, 29 MZs
Products = 3
Outsourced = 3
num_Scenarios = 200
Manufacturing_plants = 6
Distribution = 4
Market = 29

# Cost of opening/establishing/operating 
f_i = [2070000, 2000000, 1656000]*2
f_j = [2070000, 2000000, 1656000, 1800000]

# In-house produce + transport 

np.random.seed(0)
Manufacturing_costs = np.random.uniform(0.1,0.2, (Manufacturing_plants,Products))

Transportation_i_j = np.zeros((Products, Manufacturing_plants, Distribution))
for m in range(Products):
    for i in range(Manufacturing_plants):
        for j in range(Distribution):
            Transportation_i_j[m][i][j] = distances_i_j[i][j]/1000

Transportation_j_k = np.zeros((Products, Distribution, Market))
for m in range(Products):
    for j in range(Distribution):
        for k in range(Market):
            Transportation_j_k[m][j][k] = distances_j_k[j][k]/1000

# Capacities of plants in squared feet

Capacities_i = [103500, 100000, 82800]*2

Capacities_j = [103500, 100000, 82800, 90000]

# Quantity supplier can provide 

Capacities_l = np.zeros((Products, Outsourced))
Capacities_l[0][0] = 1750000
Capacities_l[1][1] = 1800000
Capacities_l[2][2] = 1900000

# Cost of purchasing from suppliers

levels = 2
Supplier_cost = np.zeros((levels, Products, Outsourced))
Supplier_cost[0][0][0] = 10
Supplier_cost[0][1][1] = 5
Supplier_cost[0][2][2] = 7

Supplier_cost[1][0][0] = 11
Supplier_cost[1][1][1] = 6
Supplier_cost[1][2][2] = 8

# Cost of transporting from suppliers

T_O_DC = np.zeros((Products, Outsourced, Distribution))
for m in range(Products):
    for l in range(Outsourced):
        for j in range(Distribution):
            T_O_DC[m][l][j] = distances_l_j[l][j]/1000

T_O_MZ = np.zeros((Products, Outsourced, Market))
for m in range(Products):
    for l in range(Outsourced):
        for k in range(Market):
            T_O_MZ[m][l][k] = distances_l_k[l][k]/1000

# volume of products

volume = np.random.uniform(0.01, 0.03,(Products))

# unit cost of lost sales 

lost_sales = [[10, 5, 7]]*Market


# demand of each product/ scenario
demand = np.zeros((num_Scenarios, Products, Market))
np.random.seed(0)
for s in range(num_Scenarios):
    for k in range(Market):
        for m in range(Products):
            demand[s][m][k] = np.round(np.random.normal(distribution_mat[m][0], distribution_mat[m][1]))

# Compatibilities
compatibility = np.ones((Products, Manufacturing_plants))



In [78]:
# save everything to instance folder  

np.savetxt(path + 'Input_Data/Instance_5/OpenMP_5.txt', f_i)
np.savetxt(path + 'Input_Data/Instance_5/OpenDC_5.txt', f_j)
np.savetxt(path + 'Input_Data/Instance_5/Manufacturing_5.txt', Manufacturing_costs)
np.savetxt(path + 'Input_Data/Instance_5/TransMPDC_5.txt', Transportation_i_j.reshape((Products*Manufacturing_plants, Distribution)))
np.savetxt(path + 'Input_Data/Instance_5/TransDCMZ_5.txt', Transportation_j_k.reshape((Products*Distribution, Market)))
np.savetxt(path + 'Input_Data/Instance_5/CapacitiesMP_5.txt', Capacities_i)
np.savetxt(path + 'Input_Data/Instance_5/CapacitiesDC_5.txt', Capacities_j)
np.savetxt(path + 'Input_Data/Instance_5/CapacitiesOutsource_5.txt', Capacities_l)
np.savetxt(path + 'Input_Data/Instance_5/SupplierCost_5.txt', Supplier_cost.reshape((levels*Products, Outsourced)))
np.savetxt(path + 'Input_Data/Instance_5/TransSupplierDC_5.txt', T_O_DC.reshape((Products*Outsourced, Distribution)))
np.savetxt(path + 'Input_Data/Instance_5/TransSupplierMZ_5.txt', T_O_MZ.reshape((Products*Outsourced, Market)))
np.savetxt(path + 'Input_Data/Instance_5/Volume_5.txt', volume)
np.savetxt(path + 'Input_Data/Instance_5/LostSales_5.txt', lost_sales)
np.savetxt(path + 'Input_Data/Instance_5/Demand_5.txt', demand.reshape((num_Scenarios*Products, Market)))
np.savetxt(path + 'Input_Data/Instance_5/Compatibilities_5.txt', compatibility)


In [79]:
np.sum(demand[0])

8849033.0

## Meat Products

In [38]:
# open location data
with open (path + "Input_Data/Instance_6/MP_locations_6.txt") as f:
    MP_locations = [tuple(map(float, i.split('\t'))) for i in f]

with open(path + "Input_Data/Instance_6/outsource_locations_6.txt") as f:
    outsource_locations = [tuple(map(float, i.split('\t'))) for i in f]

In [39]:
# Plants to Distribution Centres
distances_i_j = []
for loc1 in range(len(MP_locations)):
    temp_dist = []
    for loc2 in range(len(DC_locations)):
        temp_dist.append(float(str(geopy.distance.geodesic(MP_locations[loc1], DC_locations[loc2]))[:-3]))
    distances_i_j.append(temp_dist)

In [40]:
# Outsourced Facilities to Distribution Centres
distances_l_j = []
for loc1 in range(len(outsource_locations)):
    temp_dist = []
    for loc2 in range(len(DC_locations)):
        temp_dist.append(float(str(geopy.distance.geodesic(outsource_locations[loc1], DC_locations[loc2]))[:-3]))
    distances_l_j.append(temp_dist)

In [41]:
# Outsourced Facilities to Market Zones
distances_l_k = []
for loc1 in range(len(outsource_locations)):
    temp_dist = []
    for loc2 in range(len(market_locations)):
        temp_dist.append(float(str(geopy.distance.geodesic(outsource_locations[loc1], market_locations[loc2]))[:-3]))
    distances_l_k.append(temp_dist)

In [42]:
p1_mean = 137000
p2_mean = 135000
p3_mean = 133000

p1_sd = 2650
p2_sd = 8125
p3_sd = 4000

distribution_mat = [[p1_mean, p1_sd],
                  [p2_mean, p2_sd],
                  [p3_mean, p3_sd]]

In [65]:
## 6 MPs, 4 DCs, 29 MZs
Products = 3
Outsourced = 3
num_Scenarios = 200
Manufacturing_plants = 6
Distribution = 4
Market = 29

# Cost of opening/establishing/operating 
f_i = [2070000, 2000000, 1656000]*2
f_j = [2070000, 2000000, 1656000, 1800000]

# In-house produce + transport 

np.random.seed(0)
Manufacturing_costs = np.random.uniform(0.1,0.2, (Manufacturing_plants,Products))

Transportation_i_j = np.zeros((Products, Manufacturing_plants, Distribution))
for m in range(Products):
    for i in range(Manufacturing_plants):
        for j in range(Distribution):
            if i == 0:
                Transportation_i_j[m][i][j] = distances_i_j[i][j]/10000
            else: 
                Transportation_i_j[m][i][j] = distances_i_j[i][j]/1000


Transportation_j_k = np.zeros((Products, Distribution, Market))
for m in range(Products):
    for j in range(Distribution):
        for k in range(Market):
            Transportation_j_k[m][j][k] = distances_j_k[j][k]/1000

# Capacities of plants in squared feet

Capacities_i = [103500, 100000, 82800]*2

Capacities_j = [103500, 100000, 82800, 90000]

# Quantity supplier can provide 

Capacities_l = np.zeros((Products, Outsourced))
Capacities_l[0][2] = 1250000
Capacities_l[1][1] = 1300000
Capacities_l[2][0] = 1400000

# Cost of purchasing from suppliers

levels = 2
Supplier_cost = np.zeros((levels, Products, Outsourced))
Supplier_cost[0][0][2] = 11
Supplier_cost[0][1][1] = 9
Supplier_cost[0][2][0] = 7

Supplier_cost[1][0][2] = 12
Supplier_cost[1][1][1] = 10
Supplier_cost[1][2][0] = 8

# Cost of transporting from suppliers

T_O_DC = np.zeros((Products, Outsourced, Distribution))
for m in range(Products):
    for l in range(Outsourced):
        for j in range(Distribution):
            T_O_DC[m][l][j] = distances_l_j[l][j]/1000

T_O_MZ = np.zeros((Products, Outsourced, Market))
for m in range(Products):
    for l in range(Outsourced):
        for k in range(Market):
            T_O_MZ[m][l][k] = distances_l_k[l][k]/1000

# volume of products

volume = np.random.uniform(0.01, 0.02,(Products))

# unit cost of lost sales 

lost_sales = [[11, 9, 7]]*Market


# demand of each product/ scenario
demand = np.zeros((num_Scenarios, Products, Market))
np.random.seed(0)
for s in range(num_Scenarios):
    for k in range(Market):
        for m in range(Products):
            demand[s][m][k] = np.round(np.random.normal(distribution_mat[m][0], distribution_mat[m][1]))

# Compatibilities
compatibility = [[0, 1, 0, 1, 1, 0],
                 [1, 1, 0, 1, 0, 0],
                 [0, 0, 1, 0, 0, 1]]

In [66]:
np.savetxt(path + 'Input_Data/Instance_6/OpenMP_6.txt', f_i)
np.savetxt(path + 'Input_Data/Instance_6/OpenDC_6.txt', f_j)
np.savetxt(path + 'Input_Data/Instance_6/Manufacturing_6.txt', Manufacturing_costs)
np.savetxt(path + 'Input_Data/Instance_6/TransMPDC_6.txt', Transportation_i_j.reshape((Products*Manufacturing_plants, Distribution)))
np.savetxt(path + 'Input_Data/Instance_6/TransDCMZ_6.txt', Transportation_j_k.reshape((Products*Distribution, Market)))
np.savetxt(path + 'Input_Data/Instance_6/CapacitiesMP_6.txt', Capacities_i)
np.savetxt(path + 'Input_Data/Instance_6/CapacitiesDC_6.txt', Capacities_j)
np.savetxt(path + 'Input_Data/Instance_6/CapacitiesOutsource_6.txt', Capacities_l)
np.savetxt(path + 'Input_Data/Instance_6/SupplierCost_6.txt', Supplier_cost.reshape((levels*Products, Outsourced)))
np.savetxt(path + 'Input_Data/Instance_6/TransSupplierDC_6.txt', T_O_DC.reshape((Products*Outsourced, Distribution)))
np.savetxt(path + 'Input_Data/Instance_6/TransSupplierMZ_6.txt', T_O_MZ.reshape((Products*Outsourced, Market)))
np.savetxt(path + 'Input_Data/Instance_6/Volume_6.txt', volume)
np.savetxt(path + 'Input_Data/Instance_6/LostSales_6.txt', lost_sales)
np.savetxt(path + 'Input_Data/Instance_6/Demand_6.txt', demand.reshape((num_Scenarios*Products, Market)))
np.savetxt(path + 'Input_Data/Instance_6/Compatibilities_6.txt', compatibility)



In [67]:
Supplier_cost

array([[[ 0.,  0., 11.],
        [ 0.,  9.,  0.],
        [ 7.,  0.,  0.]],

       [[ 0.,  0., 12.],
        [ 0., 10.,  0.],
        [ 8.,  0.,  0.]]])

In [68]:
np.sum(demand[0][0])*0.027

107562.168

In [53]:
demand[0]

array([[141675., 142938., 139518., 138088., 139017., 137884., 137830.,
        138732., 143015., 136504., 137411., 131751., 140260., 136199.,
        132478., 135839., 132723., 138025., 136925., 137802., 135218.,
        132425., 132680., 137138., 140019., 135185., 136174., 139387.,
        140944.],
       [138251., 150174., 133770., 136170., 135989., 147139., 128060.,
        142024., 123183., 147454., 138073., 132173., 144769., 126481.,
        150850., 124821., 133271., 130850., 138480., 129846., 132079.,
        136442., 138760., 140924., 124967., 127925., 135456., 138784.,
        150404.],
       [136915., 129091., 132587., 138817., 134775., 132179., 122788.,
        130031., 133183., 138877., 129449., 133625., 131451., 127320.,
        130961., 136110., 129418., 128277., 133266., 131549., 129747.,
        131393., 129371., 133516., 134609., 130685., 128339., 126855.,
        137715.]])

In [64]:
T_O_MZ

array([[[1.46547286, 1.45426787, 1.45156884, 1.45608613, 1.47364895,
         1.46379589, 1.46147203, 1.44814365, 1.46419559, 1.4719215 ,
         1.47123346, 1.46908147, 1.46732536, 1.46503236, 1.46639573,
         1.46052335, 1.46732335, 1.47512985, 1.47668552, 1.47908124,
         1.47376393, 1.4736357 , 1.47215424, 1.46906739, 1.46957798,
         1.46979644, 1.47062956, 1.48350097, 1.50514435],
        [0.05952008, 0.05233715, 0.04696935, 0.04932196, 0.07608382,
         0.06676556, 0.06302007, 0.05843384, 0.06852485, 0.08006451,
         0.07887114, 0.07730682, 0.0776461 , 0.07829991, 0.08002489,
         0.08115499, 0.09224511, 0.07827765, 0.0817074 , 0.08663492,
         0.07931287, 0.07789795, 0.0753887 , 0.07198679, 0.07442899,
         0.07570652, 0.07704886, 0.10526128, 0.13660169],
        [0.37616522, 0.37838791, 0.3840671 , 0.38391828, 0.35773237,
         0.36449256, 0.36817521, 0.36928362, 0.3624167 , 0.35138629,
         0.35258074, 0.35355382, 0.3524011 , 0.3508404 ,