In [6]:
import numpy as np
import itertools
import random
from statistics import stdev
import math
import ast

In [7]:
p_running = 0.9
p_failure = 1 - p_running
path = '/home/dkabe/Model_brainstorming/SAA_Analysis_v3/'

In [8]:
N = [50, 100, 200, 300, 400, 500]
batches = 30
Products = 3
Market = 29
batches = 30
demand_realization = 25
text_file = open(path + 'Disruption_scenarios.txt', "r")
ls = text_file.read().split('\n')[:-1]
Scenarios = list(map(lambda x: ast.literal_eval(x), ls))
Probabilities = np.loadtxt(path + "disruption_probabilities.txt")

In [9]:
p1_mean = 137000
p2_mean = 135000
p3_mean = 133000

p1_sd = 2650
p2_sd = 8125
p3_sd = 4000

distribution_mat = [[p1_mean, p1_sd],
                  [p2_mean, p2_sd],
                  [p3_mean, p3_sd]]

In [10]:
np.random.seed(1)
demand = np.zeros((demand_realization, Products, Market))
for r in range(demand_realization):
    demand[r][0] = np.round(np.random.normal(distribution_mat[0][0], distribution_mat[0][1], size = 29))
    demand[r][1] = np.round(np.random.normal(distribution_mat[1][0], distribution_mat[1][1], size = 29))
    demand[r][2] = np.round(np.random.normal(distribution_mat[2][0], distribution_mat[2][1], size = 29))
#np.savetxt("/home/dkabe/Model_brainstorming/SAA_Analysis_v3/demand.txt", demand)

In [22]:
S = demand_realization*Scenarios
S_demand = []
for r in range(demand_realization):
    S_demand.append(list(demand[r])*25)

In [23]:
S_demand

[[array([141305., 135379., 135600., 134157., 139293., 130901., 141624.,
         134983., 137845., 136339., 140875., 131541., 136146., 135982.,
         140004., 134085., 136543., 134674., 137112., 138544., 134083.,
         140034., 139389., 138332., 139387., 135188., 136674., 134520.,
         136290.]),
  array([139309., 129380., 131776., 129417., 128133., 129546., 134897.,
         125922., 136905., 148486., 141029., 133441., 127788., 128929.,
         148751., 135413., 129824., 136551., 152065., 135976., 140015.,
         137439., 132138., 125717., 132162., 133303., 139766., 141817.,
         142565.]),
  array([134142., 136541., 129982., 138011., 135052., 131808., 134954.,
         132698., 137527., 139079., 141742., 127414., 127224., 130982.,
         133640., 136505., 134263., 124911., 131775., 136312., 133920.,
         136048., 132111., 132197., 133746., 134640., 133793., 133476.,
         130317.]),
  array([141305., 135379., 135600., 134157., 139293., 130901., 141624.,
    

In [24]:
len(S_demand)

25

In [21]:
list(demand[0])*25

[array([141305., 135379., 135600., 134157., 139293., 130901., 141624.,
        134983., 137845., 136339., 140875., 131541., 136146., 135982.,
        140004., 134085., 136543., 134674., 137112., 138544., 134083.,
        140034., 139389., 138332., 139387., 135188., 136674., 134520.,
        136290.]),
 array([139309., 129380., 131776., 129417., 128133., 129546., 134897.,
        125922., 136905., 148486., 141029., 133441., 127788., 128929.,
        148751., 135413., 129824., 136551., 152065., 135976., 140015.,
        137439., 132138., 125717., 132162., 133303., 139766., 141817.,
        142565.]),
 array([134142., 136541., 129982., 138011., 135052., 131808., 134954.,
        132698., 137527., 139079., 141742., 127414., 127224., 130982.,
        133640., 136505., 134263., 124911., 131775., 136312., 133920.,
        136048., 132111., 132197., 133746., 134640., 133793., 133476.,
        130317.]),
 array([141305., 135379., 135600., 134157., 139293., 130901., 141624.,
        134983., 137